[2023-06-13T09:04:31.712+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Create_psql_schema manual__2023-06-13T09:04:30.782788+00:00 [queued]>
[2023-06-13T09:04:31.721+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_psql_redshift_dag.Create_psql_schema manual__2023-06-13T09:04:30.782788+00:00 [queued]>
[2023-06-13T09:04:31.722+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T09:04:31.722+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-06-13T09:04:31.722+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T09:04:31.733+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): Create_psql_schema> on 2023-06-13 09:04:30.782788+00:00
[2023-06-13T09:04:31.740+0000] {standard_task_runner.py:55} INFO - Started process 205 to run task
[2023-06-13T09:04:31.749+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_psql_redshift_dag', 'Create_psql_schema', 'manual__2023-06-13T09:04:30.782788+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dags_setup.py', '--cfg-path', '/tmp/tmpk0vg77jx']
[2023-06-13T09:04:31.756+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask Create_psql_schema
[2023-06-13T09:04:31.848+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL_psql_redshift_dag.Create_psql_schema manual__2023-06-13T09:04:30.782788+00:00 [running]> on host 18c8ccfcc77e
[2023-06-13T09:04:31.877+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'Create_psql_schema', field 'sql'. Template: 'create_pgsql_schema.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_pgsql_schema.sql
[2023-06-13T09:04:31.878+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_pgsql_schema.sql
[2023-06-13T09:04:31.894+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_psql_redshift_dag, task_id=Create_psql_schema, execution_date=20230613T090430, start_date=20230613T090431, end_date=20230613T090431
[2023-06-13T09:04:31.903+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task Create_psql_schema (create_pgsql_schema.sql; 205)
[2023-06-13T09:04:31.919+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-13T09:04:31.942+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
